// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.
let fib = a => {
    if (a === 2) {
        return 2;
    } else if (a === 1) {
        return 1;
    } else {
        return fib(a - 1) + fib(a - 2);
    }
}

let sumEvenFib = _ => {
    let sum = 0;
    let i = 2;
    while (fib(i) < 4000000) {
        sum += fib(i);
        i += 3;
    }
    return sum;
}

sumEvenFib();
